name: Release Build

on:
  release:
    types: [published]

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: ha-airplay2
  RELEASE_TAG: ${{ github.event.release.tag_name }}

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.lowercase_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
          submodules: 'true'
          fetch-depth: 0

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

      - name: Lowercase matrix image names
        id: lowercase_matrix
        run: |
          MATRIX='${{ steps.matrix.outputs.matrix }}'
          echo "matrix=$(echo "$MATRIX" | jq -c 'walk(if type == "string" then ascii_downcase else . end)')" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read # To check out the code
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push built images to GitHub Container Registry
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
          submodules: 'true'
          fetch-depth: 0

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          file: Airplay2/Dockerfile
          context: Airplay2/
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ env.RELEASE_TAG }}
            latest
          push: "true"
          version: ${{ env.RELEASE_TAG }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push the manifest to GitHub Container Registry
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-prefix: ghcr.io/johannvr
          image-name: ${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ env.RELEASE_TAG }}
            latest
